config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
  resources :likes

   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    has_one_attached :image

    belongs_to :user
    has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: {scope: :article_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @article.view = @article.view.to_i + 1
    @article.update_attribute("view", @article.view)
  end
  
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    if user_signed_in?
      @article = Article.new(article_params)

      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Article was successfully created.' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.user_id == current_user.id
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @article.user_id == current_user.id
        @article.destroy
        respond_to do |format|
          format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
          format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :discription, :image, :user_id, :like_id, :view)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @like = current_user.likes.new(like_params)
            if !@like.save
                flash[:alert] = "You Already Like This"
            end
            redirect_back(fallback_location: root_path)
        end

    def destroy
        @like = current_user.likes.find(params[:id])
        @like.destroy
    end
    
    def like_params
        params.require(:like).permit(:post_id)
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>

    <div class="field-1">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field-1">
      <%= form.label :description %>
      <%= form.text_area :discription %>
    </div>
  
    <div class="field-1">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  
    <div class="actions">
      <%= form.submit class: "btn1 btn-primary1" %>
    </div>
  <% end %>
  

app/views/articles/edit.html.erb
<section class="project-2">
<h2 class="vev1">Editing article</h2>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>
</section>

app/views/articles/index.html.erb
<section class="project-2">
    <h2 class="vev">Articles</h2>
      <div class="container projects2-container">
         <% @articles.each do |article| %>
            <article class="project2">
              <div class="project2-img">
                <% if article.image.attached? %>
                    <%= image_tag article.image, class: "article-image" %>
                <% end %>
              </div>
      <p class="vev"><%= article.title %></p>
      <a><%= link_to "Learn More", article_path(article.id), class:"btn1 btn-primary1"%></a>
      
            </article>
          <% end %>
      </div>
        <%= link_to 'New Article', new_article_path, class: "btn1 btn-primary1 fef" %>
</section>

app/views/articles/new.html.erb
<section class="project-2">
<h2 class="vev1">New Article</h2>
<div class="container projects2-container">

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>
</div>
</section>

app/views/articles/show.html.erb
<section class="project-2">
    <h2 class="vev1"><%= @article.title %></h2>
        <div class="container1">
                <div class="show-articl ">
                    <% if @article.image.attached? %>
                    <%= image_tag @article.image %>
                    <% end %>
                </div>
                <div class="article-dis">
                    <p class="vev"><%= @article.discription %></p>
                </div>
                <h6 class="time">
                    <%= time_ago_in_words(@article.created_at)%>  ago
                </h6>
                <h6 class="time">
                    <%= @article.view %>
                </h6>
                <% if current_user %>
                <h6 class="time">
                <%= button_to "likes", likes_path, params: {like: {article_id:@article.id}} %>
                <%= @article.likes %>
                </h6>
                <% end%>
        </div>
            <div class="link-v">
                <h6>
                    <%= link_to 'Back', articles_path, class:"btn2 btn-primary2" %>
                </h6>
                <h6>
                    <%= link_to 'Edit', edit_article_path(@article), class:"btn2 btn-primary2" %>
                </h6>
            </div>

            <h6>
            <%= button_to "Destroy this article", @article, method: :delete %>
        </h6>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carcraze</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
  <%= render partial: "shared/navbar"%>

    <%= yield %>
    <%= render partial: "shared/footer"%>
  </body>
</html>

app/views/main/index.html.erb
<section class="project-2">

    
  </section>

app/views/shared/_footer.html.erb
<footer class="footer">
        <div class="container footer-container">
            <div class="footer-1">
                <h4 class="footer-logo vev1">C A R C R A Z E</h4>
                <p class="vev1">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, non
                </p>
            </div>

            <div class="footer-2"> 
                <h4 class="vev1">Parmalinks</h4>
                <ul class="parmalinks vev1 ">
                    <li>Home</li>
                    <li>Creat Account</li>
                    <li>Blogs</li>
                </ul>
            </div>

            <div class="footer-3">
                <h4 class="vev1">Privacy</h4>
                <ul class="privacy vev1">
                    <li>privacy Policy</li>
                    <li>Terms and conditions</li>
                    <li>Refund Policy</li>
                </ul>
            </div>
            <div class="footer-4">
                <h4 class="vev1">Contact Us</h4>
                <div class="vev1">
                    <p>+92 310 5643 141</p>
                    <p>uk4248609@gmail.com</p>
                </div>
            
            <ul class="footer-social"> 
                <li>
                    <i class="uli uil-facebook-f"></i>
                </li>
                <li>
                    <a href="#"><i class="uli uil-instagram-alt"></i></a>
                </li>
                <li>
                    <a href="#"><i class="uli uil-twitter"></i></a>
                </li>
                <li>
                    <a href="#"><i class="uli uil-linkedin-alt"></i></a>
                </li>
            </ul>
        </div>
        </div>
        <div class="footer-copyright">
            <small class="vev1">Copyright &copy; Car Modification Services</small>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<nav class=" navbar-expand-lg nav1 window-scroll" >
  <div class="container nav-container">
    <a class="navbar-brand text-white">C A R C R A Z E
    </a>

    <button class="navbar-toggler nv-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">  
              <ul class="navbar-nav gap">
                  <li class="nav-item">
                    <%= link_to "New Article", new_article_path, class: "nav-link"%>
                  </li>
                  <li class="nav-item">
                  <%= link_to "Articles", articles_path, class:"nav-link"%>
                  </li>
                </ul>
        </div>

    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap">
        <% if user_signed_in? %>
                <li class="nav-item nav-s">
                    <%= current_user.email %>
                </li>
                <li class="nav-item nav-s">
                    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item nav-s">
                    <%= link_to "Sign Up", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item nav-s">
                    <%= link_to "Login", new_user_registration_path, class: "nav-link" %>
                </li>
        <% end %>
    </ul>

    </div>
  </div>
</nav>